
class ID:
    STAIRS_SIMPLE = "STAIRS_SIMPLE"
    STAIRS_DEPENDENT = "STAIRS_DEPENDENT"
    FIXED_BUY_COST_S = "FIXED_BUY_COST_S"
    FIXED_BUY_COST_D = "FIXED_BUY_COST_D"
    STAIRS_PROGRESSIVE_S = "STAIRS_PROGRESSIVE_S"
    STAIRS_PROGRESSIVE_D = "STAIRS_PROGRESSIVE_D"
    SOFT_COST_INCREASE_S = "SOFT_COST_INCREASE_S"
    SOFT_COST_INCREASE_D = "SOFT_COST_INCREASE_D"
