
class ID:
    SIMPLE = "SIMPLE"
    DEPENDENT = "DEPENDENT"
    COST_COMPUTED_S = "COST_COMPUTED_S"
    COST_COMPUTED_D = "COST_COMPUTED_D"
    FIXED_BUY_COST_S = "FIXED_BUY_COST_S"
    FIXED_BUY_COST_D = "FIXED_BUY_COST_D"
    SOFT_COST_INCREASE_S = "SOFT_COST_INCREASE_S"
    SOFT_COST_INCREASE_D = "SOFT_COST_INCREASE_D"
